apiVersion: v1
kind: Template
metadata:
  annotations:
    desrciption: "Template for generating binary builds."
    tags: ""
parameters:
- name: "APP_NAME"
  displayName: "Application name"
  description: "Name of your application"
  required: true
- name: "BUILDER_IMAGE"
  displayName: "Builder Image"
  description: "Builder image which will be used as a base image"
  required: true
- name: "OUTPUT_IMAGESTREAM"
  displayName: "Output ImageStream"
  description: "ImageStream created as a result of the build"
  required: true
objects:
- apiVersion: v1
  items:
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        labels:
          build: $OUTPUT_IMAGESTREAM
        name: $OUTPUT_IMAGESTREAM
      spec:
        output:
          to:
            kind: ImageStreamTag
            name: $OUTPUT_IMAGESTREAM
        source:
          type: Binary
        strategy:
          sourceStrategy:
            from:
              kind: ImageStreamTag
              name: $BUILDER_IMAGE
          type: Source
