apiVersion: v1
kind: Template
metadata:
  annotations:
    desrciption: "Template for generating binary builds."
    tags: ""
parameters:
- name: "APP_NAME"
  displayName: "Application name"
  description: "Name of your application"
  required: true
- name: "BUILDER_IMAGE"
  displayName: "Builder Image"
  description: "Builder image which will be used as a base image"
  required: true
#- name: "OUTPUT_IMAGESTREAM"
#  displayName: "Output ImageStream"
#  description: "ImageStream created as a result of the build"
#  required: true
- name: "OUTPUT_IMAGESTREAM_TAG"
  displayName: "Output ImageStream"
  description: "ImageStream created as a result of the build"
  value: "latest"

objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      application: ${APP_NAME}
  spec:
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${BUILDER_IMAGE}
    source:
      type: Binary
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:${OUTPUT_IMAGESTREAM_TAG}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      application: ${APP_NAME}
  spec:
    tags:
    - name: build
    - name: stage
      from:
        kind: ImageStreamTag
        name: build
    - name: prod 
      from:
        kind: ImageStreamTag
        name: build
