apiVersion: v1
kind: Template
metadata:
  annotations:
    desrciption: "Template for generating BuildConfigs with jenkinsPipelineStrategy."
    tags: ""
parameters:
- name: "APP_NAME"
  displayName: "Application name"
  description: "Name of your application"
  required: true
- name: "JENKINSFILE_PATH"
  displayName: "Jenkinsfile path"
  description: "Path to Jenkinsfile. (e.g. helloworld/Jenkinsfile)"
  required: true
  value: "./Jenkinsfile"
- name: "GIT_URL"
  displayName: "Git URL"
  description: "URL to git source repository containing Jenkinsfile. (e.g. https://github.com/tnozicka/jboss-eap-quickstarts.git)"
  required: true
- name: "GIT_REF"
  displayName: "Git Reference"
  description: "Git reference. (branch, ...)"
  value: "master"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      application: ${APP_NAME}
  spec:
    triggers:
      - type: ConfigChange
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${JENKINSFILE_PATH}
    source:
      type: git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
